version: '3'
services:
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: "no"
  php:
    build: .docker/php/cli
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app
  phpunit:
    build: .docker/php/cli
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
  fpm:
    build: .docker/php/fpm
    restart: always
    volumes:
      - .:/app
  nginx:
    image: nginx:1.17.8-alpine
    ports:
      - 8080:80
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - .conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
  flipt:
    image: markphelps/flipt
    ports:
      - 9000:9000
      - 8081:8080
  protoc:
    build: .docker/php/cli
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: protoc
